jwt:
 secret: "password"

server:
 port: 8081
# error:
#  whitelabel:
#   enabled: false # this setting will stop Spring from sending the whitelabel error page and will allow the servlet handle the 404 not found.
# White label error page is coming from: ErrorMvcAutoConfiguration

spring:
 datasource:
  url: jdbc:mysql://localhost:3306/support
  password: mysqldb
  username: root
 jpa:
  show-sql: true
  hibernate: 
   ddl-auto: update
 properties: 
  hibernate: 
   dialect: org.hibernate.dialect.MySQL8Dialect
